os:
  editPreset: 'vim'

keybinding:
  universal:
    optionMenu: 'x'
    filteringMenu: '<c-f>'

  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'

customCommands:
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    command: 'git commit --allow-empty -m "empty"'
    loadingText: 'Committing empty commit...'

  - key: 'P'
    description: 'Push to gerrit'
    command: 'git pushgerrit {{.SelectedLocalCommit.Sha}}'
    context: 'commits'
    loadingText: 'Pushing'

  - key: '<c-s>'
    description: Sign off last commit
    context: 'commits'
    command: 'git commit --amend --signoff'
    subprocess: true
