#!/bin/bash

alias wcmd="cmd.exe /C"
alias wusb="cmd.exe /C usbipd wsl"
alias wusb-list="cmd.exe /C usbipd wsl list"
alias wusb-attach="cmd.exe /C usbipd wsl attach"

export LIBGL_ALWAYS_INDIRECT=1
export DISPLAY=localhost:0.0
